name: foodguru
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  google_fonts: ^3.0.1
  rxdart: ^0.27.7
  url_launcher: ^6.1.7
  image_picker: ^1.0.0
  path_provider: ^2.0.11
  fluttertoast: ^8.1.2
  dio: ^4.0.1
  google_sign_in: ^5.4.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.14.0
  get: ^4.6.5
  cloud_firestore: ^4.8.1
  flutter_screenutil: ^5.7.0
  logger: ^1.4.0
  smooth_page_indicator: ^1.1.0
  control_style: ^0.0.3
  flutter_spinkit: ^5.2.0
  lottie:
  pinput: ^2.2.31
  firebase_storage: ^11.2.3
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  permission_handler: ^10.3.0
  geocoding: ^2.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  flutter_rating_bar: ^4.0.1
  flutter_polyline_points: ^1.0.0
  intl: ^0.18.1
  location: ^5.0.0
  maps_launcher: ^2.2.0
  translator: ^0.1.7
  responsive_framework: ^1.0.0
  sembast_web: ^2.1.3
#  idb_sqflite: ^1.3.1
#  sqlite3: ^2.1.0
#  sqflite_common_ffi: ^2.3.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core_platform_interface: ^4.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/SVG/
    - assets/JsonData/
  fonts: 

    - family: Inter
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400