import 'package:foodguru/app_values/export.dart';

class DummyLists {
  static List<Map<String, dynamic>> relatedRestaurantList = [
    {
      DatabaseValues.columnRestaurantId: 1,
      DatabaseValues.columnRestaurantName: "Starbucks",
      DatabaseValues.columnLogo: ImageConstant.imagesIcStarbucks,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCategoryId: [1, 2, 3].join(','),
      DatabaseValues.columnDescription: "Coffee Company",
    },
    {
      DatabaseValues.columnRestaurantId: 1,
      DatabaseValues.columnRestaurantName: "स्टारबक्स",
      DatabaseValues.columnLogo: ImageConstant.imagesIcStarbucks,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCategoryId: [1, 2, 3].join(','),
      DatabaseValues.columnDescription: "कॉफ़ी कंपनी",
    },
    {
      DatabaseValues.columnRestaurantId: 2,
      DatabaseValues.columnRestaurantName: "Mc Donald’s",
      DatabaseValues.columnLogo: ImageConstant.imagesIcMcdonals,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCategoryId: [2, 4, 3].join(','),
      DatabaseValues.columnDescription: "Freshly prepared food items.",
    },
    {
      DatabaseValues.columnRestaurantId: 2,
      DatabaseValues.columnRestaurantName: "मैकडॉनल्ड्स",
      DatabaseValues.columnLogo: ImageConstant.imagesIcMcdonals,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCategoryId: [2, 4, 3].join(','),
      DatabaseValues.columnDescription: "ताजा तैयार खाना",
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnRestaurantName: "Domino's Pizza",
      DatabaseValues.columnLogo: ImageConstant.imagesIcDominos,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCategoryId: [9, 4, 5].join(','),
      DatabaseValues.columnDescription: "Freshly Baked Pizza's",
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnRestaurantName: "डोमिनोज पिज़्ज़ा",
      DatabaseValues.columnLogo: ImageConstant.imagesIcDominos,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCategoryId: [9, 4, 5].join(','),
      DatabaseValues.columnDescription: "ताज़ा बेक किया हुआ पिज़्ज़ा",
    },
    {
      DatabaseValues.columnRestaurantId: 4,
      DatabaseValues.columnRestaurantName: "Sindhi Sweets",
      DatabaseValues.columnLogo: ImageConstant.imagesIcSindhiSweets,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCategoryId: [3, 5, 4].join(','),
      DatabaseValues.columnDescription: "Pure and Delightful sweets",
    },
    {
      DatabaseValues.columnRestaurantId: 4,
      DatabaseValues.columnRestaurantName: "सिंधी स्वीट्स",
      DatabaseValues.columnLogo: ImageConstant.imagesIcSindhiSweets,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCategoryId: [3, 5, 4].join(','),
      DatabaseValues.columnDescription: "शुद्ध और आनंददायक मिठाई",
    },
    {
      DatabaseValues.columnRestaurantId: 5,
      DatabaseValues.columnRestaurantName: "Gopal's",
      DatabaseValues.columnLogo: ImageConstant.imagesIcGopals,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCategoryId: [3, 6, 9].join(','),
      DatabaseValues.columnDescription: "Sweets and Snacks",
    },
    {
      DatabaseValues.columnRestaurantId: 5,
      DatabaseValues.columnRestaurantName: "गोपालस",
      DatabaseValues.columnLogo: ImageConstant.imagesIcGopals,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCategoryId: [3, 6, 9].join(','),
      DatabaseValues.columnDescription: "मिठाइयाँ और नाश्ते",
    },
  ];
  static List<Map<String, dynamic>> mainRestaurantList = [
    {DatabaseValues.columnRestaurantName: 'Starbucks'},
    {DatabaseValues.columnRestaurantName: 'Mc Donald’s'},
    {DatabaseValues.columnRestaurantName: 'Domino\'s Pizza'},
    {DatabaseValues.columnRestaurantName: 'Sindhi Sweets'},
    {DatabaseValues.columnRestaurantName: 'Gopal\'s'},
  ];
  static List<Map<String, dynamic>> mainOutletList = [
    {
      DatabaseValues.columnRestaurantId: 1,
      DatabaseValues.columnOutlet: 'Noida'
    },
    {
      DatabaseValues.columnRestaurantId: 2,
      DatabaseValues.columnOutlet: 'Chandigarh'
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutlet: 'Ambala'
    },
    {
      DatabaseValues.columnRestaurantId: 4,
      DatabaseValues.columnOutlet: 'Mohali'
    },
    {
      DatabaseValues.columnRestaurantId: 5,
      DatabaseValues.columnOutlet: 'Kharar'
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutlet: 'Chandigarh'
    },
  ];
  static List<Map<String, dynamic>> outletList = [
    {
      DatabaseValues.columnRestaurantId: 1,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnOutlet: 'Noida',
      DatabaseValues.columnRating: '4.9',
      DatabaseValues.columnPhone: '789456123',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Noida',
      DatabaseValues.columnState: 'Uttar Pradesh',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.3657523404312,
      DatabaseValues.columnLongitude: 76.7879528709722,
      DatabaseValues.columnFreeDeliveryAbove: 700,
      DatabaseValues.columnIsDineInAvailable: 1,
      DatabaseValues.columnGstPercentage: 10,
      DatabaseValues.columnDeliveryPerKm: 5,
      DatabaseValues.columnCouponId: [2, 1, 3].join(','),

    },
    {
      DatabaseValues.columnRestaurantId: 1,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnOutlet: 'नोएडा',
      DatabaseValues.columnRating: '4.9',
      DatabaseValues.columnPhone: '789456123',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'नोएडा',
      DatabaseValues.columnState: 'उत्तर प्रदेश।',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.3657523404312,
      DatabaseValues.columnLongitude: 76.7879528709722,
      DatabaseValues.columnFreeDeliveryAbove: 700,
      DatabaseValues.columnIsDineInAvailable: 1,
      DatabaseValues.columnGstPercentage: 10,
      DatabaseValues.columnDeliveryPerKm: 5,
      DatabaseValues.columnCouponId: [2, 1, 3].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 2,
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnOutlet: 'Chandigarh',
      DatabaseValues.columnRating: '4.5',
      DatabaseValues.columnPhone: '456789213',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Chandigarh',
      DatabaseValues.columnState: 'Chandigarh',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.36517055,
      DatabaseValues.columnLongitude: 76.78773389,
      DatabaseValues.columnFreeDeliveryAbove: 399,
      DatabaseValues.columnIsDineInAvailable: 0,
      DatabaseValues.columnGstPercentage: 15,
      DatabaseValues.columnDeliveryPerKm: 4,
      DatabaseValues.columnCouponId: [1,2, 3, 4].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 2,
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnOutlet: 'चंडीगढ़',
      DatabaseValues.columnRating: '4.5',
      DatabaseValues.columnPhone: '456789213',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'चंडीगढ़',
      DatabaseValues.columnState: 'चंडीगढ़',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.36517055,
      DatabaseValues.columnLongitude: 76.78773389,
      DatabaseValues.columnFreeDeliveryAbove: 399,
      DatabaseValues.columnIsDineInAvailable: 0,
      DatabaseValues.columnGstPercentage: 15,
      DatabaseValues.columnDeliveryPerKm: 4,
      DatabaseValues.columnCouponId: [1,2, 3, 4].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnOutlet: 'Ambala',
      DatabaseValues.columnRating: '4.2',
      DatabaseValues.columnPhone: '963852711',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Ambala',
      DatabaseValues.columnState: 'Haryana',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.36609444,
      DatabaseValues.columnLongitude: 76.7865006,
      DatabaseValues.columnFreeDeliveryAbove: 499,
      DatabaseValues.columnIsDineInAvailable: 1,
      DatabaseValues.columnGstPercentage: 12,
      DatabaseValues.columnDeliveryPerKm: 10,
      DatabaseValues.columnCouponId: [1, 3, 4].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnOutlet: 'अंबाला',
      DatabaseValues.columnRating: '4.2',
      DatabaseValues.columnPhone: '963852711',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'अंबाला',
      DatabaseValues.columnState: 'हरयाणा',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.36609444,
      DatabaseValues.columnLongitude: 76.7865006,
      DatabaseValues.columnFreeDeliveryAbove: 499,
      DatabaseValues.columnIsDineInAvailable: 1,
      DatabaseValues.columnGstPercentage: 12,
      DatabaseValues.columnDeliveryPerKm: 10,
      DatabaseValues.columnCouponId: [1,3,4].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 4,
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnOutlet: 'Mohali',
      DatabaseValues.columnRating: '3.8',
      DatabaseValues.columnPhone: '7569724567',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Mohali',
      DatabaseValues.columnState: 'Punjab',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.3641114,
      DatabaseValues.columnLongitude: 76.7882489,
      DatabaseValues.columnFreeDeliveryAbove: 300,
      DatabaseValues.columnIsDineInAvailable: 0,
       DatabaseValues.columnGstPercentage: 8,
      DatabaseValues.columnDeliveryPerKm: 7,
      DatabaseValues.columnCouponId: [1,2,3,5].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 4,
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnOutlet: 'मोहाली',
      DatabaseValues.columnRating: '3.8',
      DatabaseValues.columnPhone: '7569724567',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'मोहाली',
      DatabaseValues.columnState: 'पंजाब',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.3641114,
      DatabaseValues.columnLongitude: 76.7882489,
      DatabaseValues.columnFreeDeliveryAbove: 300,
      DatabaseValues.columnIsDineInAvailable: 0,
       DatabaseValues.columnGstPercentage: 8,
      DatabaseValues.columnDeliveryPerKm: 7,
      DatabaseValues.columnCouponId: [1,2,3,5].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 5,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnOutlet: 'Kharar',
      DatabaseValues.columnRating: '4.7',
      DatabaseValues.columnPhone: '456789555',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Kharar',
      DatabaseValues.columnState: 'Punjab',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.36620461,
      DatabaseValues.columnLongitude: 76.78503713,
      DatabaseValues.columnFreeDeliveryAbove: 249,
      DatabaseValues.columnIsDineInAvailable: 1,
       DatabaseValues.columnGstPercentage: 13,
      DatabaseValues.columnDeliveryPerKm: 3,
      DatabaseValues.columnCouponId: [1,2,3,4,5].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 5,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnOutlet: 'खरड़',
      DatabaseValues.columnRating: '4.7',
      DatabaseValues.columnPhone: '456789555',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'खरड़',
      DatabaseValues.columnState: 'पंजाब',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.36620461,
      DatabaseValues.columnLongitude: 76.78503713,
      DatabaseValues.columnFreeDeliveryAbove: 249,
      DatabaseValues.columnIsDineInAvailable: 1,
       DatabaseValues.columnGstPercentage: 13,
      DatabaseValues.columnDeliveryPerKm: 3,
      DatabaseValues.columnCouponId: [1,2,3,4,5].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnOutlet: 'Chandigarh',
      DatabaseValues.columnRating: '4.5',
      DatabaseValues.columnPhone: '456789111',
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnCity: 'Chandigarh',
      DatabaseValues.columnState: 'Chandigarh',
      DatabaseValues.columnCountry: 'India',
      DatabaseValues.columnLatitude: 30.36485232,
      DatabaseValues.columnLongitude: 76.78907671,
      DatabaseValues.columnFreeDeliveryAbove: 499,
      DatabaseValues.columnIsDineInAvailable: 1,
       DatabaseValues.columnGstPercentage: 14,
      DatabaseValues.columnDeliveryPerKm: 8,
      DatabaseValues.columnCouponId: [1,2,3,4,5].join(','),
    },
    {
      DatabaseValues.columnRestaurantId: 3,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnOutlet: 'चंडीगढ़',
      DatabaseValues.columnRating: '4.5',
      DatabaseValues.columnPhone: '456789111',
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnCity: 'चंडीगढ़',
      DatabaseValues.columnState: 'चंडीगढ़',
      DatabaseValues.columnCountry: 'भारत',
      DatabaseValues.columnLatitude: 30.36485232,
      DatabaseValues.columnLongitude: 76.78907671,
      DatabaseValues.columnFreeDeliveryAbove: 499,
      DatabaseValues.columnIsDineInAvailable: 1,
       DatabaseValues.columnGstPercentage: 14,
      DatabaseValues.columnDeliveryPerKm: 8,
      DatabaseValues.columnCouponId: [1,2,3,4,5].join(','),
    },
  ];
  static List<Map<String, dynamic>> outletImages = [
    {
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcStarbucksBg,
    },
    {
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcStarbucksBg,
    },
    {
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcStarbucksBg,
    },
    {
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcStarbucksBg,
    },
    {
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
    {
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcRestaurant,
    },
  ];
  static List<Map<String, dynamic>> itemImages = [
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcDosa,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcDosa,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcDosa,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcDosa,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcDosa,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId:12,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
    {
      DatabaseValues.columnItemId:13,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcPasta,
    },
  ];
  static List<Map<String, dynamic>> itemsMainList = [
    {
      DatabaseValues.columnReference: "Nachos",
    },
    {
      DatabaseValues.columnReference: "Shahi Paneer",
    },
    {
      DatabaseValues.columnReference: "Sarso ka Saag",
    },
    {
      DatabaseValues.columnReference: "Red Sauce Pasta",
    },
    {
      DatabaseValues.columnReference: "French Fries",
    },
    {
      DatabaseValues.columnReference: "Cheesy Fries",
    },
    {
      DatabaseValues.columnReference: "White Sauce Pasta",
    },
    {
      DatabaseValues.columnReference: "Mint Mojito",
    },
    {
      DatabaseValues.columnReference: "Green Apple Mojito",
    },
    {
      DatabaseValues.columnReference: "Noodles",
    },
    {
      DatabaseValues.columnReference: "Chai",
    },
    {
      DatabaseValues.columnReference: "Chocolate Truffle",
    },
    {
      DatabaseValues.columnReference: "Oreo Shake",
    },
    // Add more items here if needed
  ];
  static List<Map<String, dynamic>> nutritionMainList = [
    {
      DatabaseValues.columnReference: "Calories",
    },
    {
      DatabaseValues.columnReference: "Fat",
    },
    {
      DatabaseValues.columnReference: "Carbs",
    },
    {
      DatabaseValues.columnReference: "Protien",
    },
    {
      DatabaseValues.columnReference: "vitamin",
    },
  ];
  static List<Map<String, dynamic>> nutritionList = [
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 500,
      DatabaseValues.columnValue: 300,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 500,
      DatabaseValues.columnValue: 300,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 50,
      DatabaseValues.columnValue: 16,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 50,
      DatabaseValues.columnValue: 16,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 100,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 100,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 25,
      DatabaseValues.columnValue: 8,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 25,
      DatabaseValues.columnValue: 8,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 5,
      DatabaseValues.columnNutritionText: "Vitamin",
      DatabaseValues.columnMaxValue: 45,
      DatabaseValues.columnValue: 10,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnNutritionId: 5,
      DatabaseValues.columnNutritionText: "विटामिन",
      DatabaseValues.columnMaxValue: 45,
      DatabaseValues.columnValue: 10,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 200,
      DatabaseValues.columnValue: 70,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 200,
      DatabaseValues.columnValue: 70,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 200,
      DatabaseValues.columnValue: 70,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 200,
      DatabaseValues.columnValue: 70,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 25,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "Calories",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnNutritionId: 1,
      DatabaseValues.columnNutritionText: "कैलोरी",
      DatabaseValues.columnMaxValue: 400,
      DatabaseValues.columnValue: 150,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "Fat",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 2,
      DatabaseValues.columnNutritionText: "फैट",
      DatabaseValues.columnMaxValue: 60,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "Carbs",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 3,
      DatabaseValues.columnNutritionText: "कार्बोहाइड्रेट",
      DatabaseValues.columnMaxValue: 80,
      DatabaseValues.columnValue: 30,
      DatabaseValues.columnLanguageId: 2,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "Protien",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 1,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnNutritionId: 4,
      DatabaseValues.columnNutritionText: "प्रोटीन",
      DatabaseValues.columnMaxValue: 35,
      DatabaseValues.columnValue: 12,
      DatabaseValues.columnLanguageId: 2,
    },
  ];
  static List<Map<String, dynamic>> itemsList = [
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnItemName: "Nachos",
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnCategoryId: [2, 1, 3].join(','),
      DatabaseValues.columnDescription: 'Crunchy Tex-Mex',
      DatabaseValues.columnItemPrice: 550,
      DatabaseValues.columnDiscountedPrice: 459,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 1,
      DatabaseValues.columnItemName: "नाचोज़",
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnCategoryId: [2, 1, 3].join(','),
      DatabaseValues.columnDescription: 'कुरकुरे टेक्स-मेक्स',
      DatabaseValues.columnItemPrice: 550,
      DatabaseValues.columnDiscountedPrice: 459,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnItemName: "Shahi Paneer",
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnCategoryId: [4, 5, 6, 8].join(','),
      DatabaseValues.columnDescription: 'Creamy Indian Delight',
      DatabaseValues.columnItemPrice: 450,
      DatabaseValues.columnDiscountedPrice: 300,
      DatabaseValues.columnPointsPerQuantity: 6,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 2,
      DatabaseValues.columnItemName: "शाही पनीर",
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnCategoryId: [4, 5, 6, 8].join(','),
      DatabaseValues.columnDescription: 'मलाईदार भारतीय खुशबू',
      DatabaseValues.columnItemPrice: 450,
      DatabaseValues.columnDiscountedPrice: 300,
      DatabaseValues.columnPointsPerQuantity: 6,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnItemName: "Sarso ka Saag",
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnCategoryId: [7, 8, 9].join(','),
      DatabaseValues.columnDescription: "Punjab's Mustard Greens",
      DatabaseValues.columnItemPrice: 250,
      DatabaseValues.columnDiscountedPrice: 200,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 3,
      DatabaseValues.columnItemName: "सरसों का साग",
      DatabaseValues.columnOutletId: 4,
      DatabaseValues.columnCategoryId: [7, 8, 9].join(','),
      DatabaseValues.columnDescription: "पंजाब की सरसों का साग",
      DatabaseValues.columnItemPrice: 250,
      DatabaseValues.columnDiscountedPrice: 200,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnItemName: "Red Sauce Pasta",
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnCategoryId: [10, 1, 2].join(','),
      DatabaseValues.columnDescription: 'Tangy Italian Noodles',
      DatabaseValues.columnItemPrice: 400,
      DatabaseValues.columnDiscountedPrice: 380,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 2,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 4,
      DatabaseValues.columnItemName: "लाल सॉस पास्ता",
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnCategoryId: [10, 1, 2].join(','),
      DatabaseValues.columnDescription: 'तीखी इटैलियन नूडल्स',
      DatabaseValues.columnItemPrice: 400,
      DatabaseValues.columnDiscountedPrice: 380,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 2,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnItemName: "French Fries",
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnCategoryId: [2, 3, 4].join(','),
      DatabaseValues.columnDescription: 'Crispy Potato Sticks',
      DatabaseValues.columnItemPrice: 120,
      DatabaseValues.columnDiscountedPrice: 100,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 5,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 5,
      DatabaseValues.columnItemName: "फ्रेंच फ्राइज",
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnCategoryId: [2, 3, 4].join(','),
      DatabaseValues.columnDescription: 'कुरकुरे आलू स्टिक्स',
      DatabaseValues.columnItemPrice: 120,
      DatabaseValues.columnDiscountedPrice: 100,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 5,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnItemName: "Cheesy Fries",
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnCategoryId: [5, 6, 7].join(','),
      DatabaseValues.columnDescription: 'Gooey Potato Perfection',
      DatabaseValues.columnItemPrice: 160,
      DatabaseValues.columnDiscountedPrice: 120,
      DatabaseValues.columnPointsPerQuantity: 3,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 6,
      DatabaseValues.columnItemName: "चीजी़ फ्राईस",
      DatabaseValues.columnOutletId: 2,
      DatabaseValues.columnCategoryId: [5, 6, 7].join(','),
      DatabaseValues.columnDescription: 'गूदे आलू परिपूर्णता',
      DatabaseValues.columnItemPrice: 160,
      DatabaseValues.columnDiscountedPrice: 120,
      DatabaseValues.columnPointsPerQuantity: 3,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnItemName: "White Sauce Pasta",
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnCategoryId: [2, 8, 9].join(','),
      DatabaseValues.columnDescription: 'Creamy Italian Delight',
      DatabaseValues.columnItemPrice: 240,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnDiscountedPrice: 200,
      DatabaseValues.columnPointsPerQuantity: 7,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 7,
      DatabaseValues.columnItemName: "सफेद सॉस पास्ता",
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnCategoryId: [2, 8, 9].join(','),
      DatabaseValues.columnDescription: 'मलाईदार इटैलियन खुशबू',
      DatabaseValues.columnItemPrice: 240,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnDiscountedPrice: 200,
      DatabaseValues.columnPointsPerQuantity: 7,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnItemName: "Mint Mojito",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [5, 6, 1].join(','),
      DatabaseValues.columnDescription: 'Refreshing Minty Sparkler',
      DatabaseValues.columnItemPrice: 190,
      DatabaseValues.columnDiscountedPrice: 150,
      DatabaseValues.columnPointsPerQuantity: 6,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 8,
      DatabaseValues.columnItemName: "मिंट मोजिटो",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [5, 6, 1].join(','),
      DatabaseValues.columnDescription: 'ताजगी वाला पुदीना',
      DatabaseValues.columnItemPrice: 190,
      DatabaseValues.columnDiscountedPrice: 150,
      DatabaseValues.columnPointsPerQuantity: 6,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnItemName: "Green Apple Mojito",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [5, 8, 2].join(','),
      DatabaseValues.columnDescription: 'Tart Apple Refresher',
      DatabaseValues.columnItemPrice: 190,
      DatabaseValues.columnDiscountedPrice: 140,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 5,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 9,
      DatabaseValues.columnItemName: "ग्रीन सेब मोजिटो",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [5, 8, 2].join(','),
      DatabaseValues.columnDescription: 'तीखे सेब की ताजगी',
      DatabaseValues.columnItemPrice: 190,
      DatabaseValues.columnDiscountedPrice: 140,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 5,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnItemName: "Noodles",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [9, 8, 10].join(','),
      DatabaseValues.columnDescription: 'Asian Stir-Fry',
      DatabaseValues.columnItemPrice: 150,
      DatabaseValues.columnDiscountedPrice: 130,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 10,
      DatabaseValues.columnItemName: "नूडल्स",
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnCategoryId: [9, 8, 10].join(','),
      DatabaseValues.columnDescription: 'एशियाई स्टिर-फ्राई',
      DatabaseValues.columnItemPrice: 150,
      DatabaseValues.columnDiscountedPrice: 130,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnItemName: "Chai",
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnCategoryId: [5, 8, 4].join(','),
      DatabaseValues.columnDescription: 'Spiced Tea Elixir',
      DatabaseValues.columnItemPrice: 50,
      DatabaseValues.columnDiscountedPrice: 30,
      DatabaseValues.columnPointsPerQuantity: 2,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 11,
      DatabaseValues.columnItemName: "चाय",
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnCategoryId: [5, 8, 4].join(','),
      DatabaseValues.columnDescription: 'मसालेदार चाय',
      DatabaseValues.columnItemPrice: 50,
      DatabaseValues.columnDiscountedPrice: 30,
      DatabaseValues.columnPointsPerQuantity: 2,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 1,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnItemName: "Chocolate Truffle",
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnCategoryId: [3, 6, 7, 5].join(','),
      DatabaseValues.columnDescription: 'Decadent Cocoa Indulgence',
      DatabaseValues.columnItemPrice: 60,
      DatabaseValues.columnDiscountedPrice: 40,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 12,
      DatabaseValues.columnItemName: "चॉकलेट ट्रफल",
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnCategoryId: [3, 6, 7, 5].join(','),
      DatabaseValues.columnDescription: 'शानदार कोको आनंद',
      DatabaseValues.columnItemPrice: 60,
      DatabaseValues.columnDiscountedPrice: 40,
      DatabaseValues.columnIsSeasonalSpecial: typeTrue,
      DatabaseValues.columnPointsPerQuantity: 4,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnItemName: "Oreo Shake",
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnCategoryId: [9, 5, 7, 6].join(','),
      DatabaseValues.columnDescription: 'Cookies & Cream Bliss',
      DatabaseValues.columnItemPrice: 120,
      DatabaseValues.columnDiscountedPrice: 110,
      DatabaseValues.columnPointsPerQuantity: 3,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnIsVeg: 0,
    },
    {
      DatabaseValues.columnItemId: 13,
      DatabaseValues.columnItemName: "ओरेओ शेक",
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnCategoryId: [9, 5, 7, 6].join(','),
      DatabaseValues.columnDescription: 'कुकीज़ और क्रीम आनंद',
      DatabaseValues.columnItemPrice: 120,
      DatabaseValues.columnDiscountedPrice: 110,
      DatabaseValues.columnPointsPerQuantity: 3,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnIsVeg: 0,
    },
  ];
  static List<Map<String, dynamic>> couponMainList = [
    {
      DatabaseValues.columnOfferType: 'percent_off',
    },
    {
      DatabaseValues.columnOfferType: 'price_off',
    },
    {
      DatabaseValues.columnOfferType: 'b1g1',
    },
    {
      DatabaseValues.columnOfferType: 'free_delivery',
    },
  ];
  static List<Map<String, dynamic>> notificationTypeList = [
    {
      DatabaseValues.columnReference: 'order placed',
    },
    {
      DatabaseValues.columnReference: 'order delivered',
    },
    {
      DatabaseValues.columnReference: 'profile edited',
    },
  ];
  static List<Map<String, dynamic>> cancelReasonMainList = [
    {
      DatabaseValues.columnTitle: 'Waiting for long time.',
    },
    {
      DatabaseValues.columnTitle: 'Unable to connect driver.',
    },
    {
      DatabaseValues.columnTitle: 'Driver denied to go to destination.',
    },
    {
      DatabaseValues.columnTitle:   'Driver denied to come to pick up.',
    },
    {
      DatabaseValues.columnTitle:   'Wrong Address shown.',
    },
    {
      DatabaseValues.columnTitle:  'The price is not reasonable.',
    },
    {
      DatabaseValues.columnTitle:  'I want to order from another restaurant.',
    },
    {
      DatabaseValues.columnTitle: 'Changed my mind.',
    },
    {
      DatabaseValues.columnTitle: 'Other.',
    },
  ];
  static List<Map<String, dynamic>> cancelReasonList = [
    {
      DatabaseValues.columnCancelReasonId: 1,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle: 'Waiting for long time',
    },
    {
      DatabaseValues.columnCancelReasonId: 1,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle: 'बहुत समय से इंतज़ार कर रहा हूँ',
    },
    {
      DatabaseValues.columnCancelReasonId: 2,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle: 'Unable to connect driver',
    },
    {
      DatabaseValues.columnCancelReasonId: 2,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle: 'ड्राइवर कनेक्ट करने में असमर्थ',
    },
    {
      DatabaseValues.columnCancelReasonId: 3,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle: 'Driver denied to go to destination',
    },
    {
      DatabaseValues.columnCancelReasonId: 3,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle: 'ड्राइवर ने गंतव्य पर जाने से इंकार कर दिया',
    },
    {
      DatabaseValues.columnCancelReasonId: 4,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle:   'Driver denied to come to pick up order',
    },
    {
      DatabaseValues.columnCancelReasonId: 4,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle:   'ड्राइवर ने ऑर्डर लेने आने से इनकार कर दिया',
    },
    {
      DatabaseValues.columnCancelReasonId: 5,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle:   'Wrong Address shown',
    },
    {
      DatabaseValues.columnCancelReasonId: 5,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle:   'गलत पता दिखाया गया',
    },
    {
      DatabaseValues.columnCancelReasonId: 6,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle:  'The price is not reasonable',
    },
    {
      DatabaseValues.columnCancelReasonId: 6,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle:  'मूल्य उचित नहीं है',
    },
    {
      DatabaseValues.columnCancelReasonId: 7,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle:  'I want to order from another restaurant',
    },
    {
      DatabaseValues.columnCancelReasonId: 7,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle:  'मैं दूसरे रेस्तरां से ऑर्डर करना चाहता हूं',
    },
    {
      DatabaseValues.columnCancelReasonId: 8,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle: 'Changed my mind',
    },
    {
      DatabaseValues.columnCancelReasonId: 8,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle: 'मैने मन बदल लिया',
    },
    {
      DatabaseValues.columnCancelReasonId: 9,
      DatabaseValues.columnLanguageId: 1,
      DatabaseValues.columnTitle: 'Other',
    },
    {
      DatabaseValues.columnCancelReasonId: 9,
      DatabaseValues.columnLanguageId: 2,
      DatabaseValues.columnTitle: 'अन्य',
    },
  ];
  static List<Map<String, dynamic>> couponList = [
    {
      DatabaseValues.columnCouponId: 1,
      DatabaseValues.columnCouponName: 'WELCOME50',
      DatabaseValues.columnDescription: '50% Off upto 100, minimum order value:200',
      DatabaseValues.columnValue: 50,
      DatabaseValues.columnImageUrl: ImageConstant.imgImage27,

      DatabaseValues.columnMinimumOrder: 200,
      DatabaseValues.columnMaximumDiscount: 100,
    },
    {
      DatabaseValues.columnCouponId: 2,
      DatabaseValues.columnCouponName: 'NEW100',
      DatabaseValues.columnDescription: '100 Rs. Off, minimum order value: 150',
      DatabaseValues.columnValue: 100,
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcHomeBanner,
      DatabaseValues.columnMinimumOrder: 150,
      DatabaseValues.columnMaximumDiscount: 100,
    },
    {
      DatabaseValues.columnCouponId: 3,
      DatabaseValues.columnCouponName: 'BOGO',
      DatabaseValues.columnImageUrl: ImageConstant.imgImage27,
      DatabaseValues.columnDescription: 'Get Buy 1 Get 1 Free, minimum order value: 500',
      DatabaseValues.columnMinimumOrder: 500,
    },
    {
      DatabaseValues.columnCouponId: 4,
      DatabaseValues.columnCouponName: 'FREEDELIVERY',
      DatabaseValues.columnImageUrl: ImageConstant.imagesIcHomeBanner,
      DatabaseValues.columnDescription: 'Get Free Delivery on your order, minimum order value: 200',
      DatabaseValues.columnMinimumOrder: 200,
    },
    {
      DatabaseValues.columnCouponId: 2,
      DatabaseValues.columnCouponName: 'OFFER100',
      DatabaseValues.columnDescription: '100 Rs. Off, minimum order value: 300',
      DatabaseValues.columnImageUrl: ImageConstant.imgImage27,
      DatabaseValues.columnValue: 100,
      DatabaseValues.columnMinimumOrder: 300,
      DatabaseValues.columnMaximumDiscount: 100,
    },
  ];

  static List<LanguageModel> languageList = <LanguageModel>[
    LanguageModel(title: 'English', locale: 'en'),
    LanguageModel(title: 'Hindi', locale: 'hi'),
  ];
  static List<CategoryModel> categoryList = <CategoryModel>[
    CategoryModel(
        categoryId: 1,
        languageId: keyEnglish,
        categoryName: 'South Indian',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 1,
        languageId: keyHindi,
        categoryName: 'दक्षिण भारतीय',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 2,
        languageId: keyEnglish,
        categoryName: 'Italian',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 2,
        languageId: keyHindi,
        categoryName: 'इटालियन',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 3,
        languageId: keyEnglish,
        categoryName: 'Chinese',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 3,
        languageId: keyHindi,
        categoryName: 'चाइनीज़',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 4,
        languageId: keyEnglish,
        categoryName: 'Indian',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 4,
        languageId: keyHindi,
        categoryName: 'इण्डियन',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 5,
        languageId: keyEnglish,
        categoryName: 'Beverages',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 5,
        languageId: keyHindi,
        categoryName: 'बेवरेज',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 6,
        languageId: keyEnglish,
        categoryName: 'Burgers',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 6,
        languageId: keyHindi,
        categoryName: 'बर्गर',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 7,
        languageId: keyEnglish,
        categoryName: 'Salads',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 7,
        languageId: keyHindi,
        categoryName: 'सलाद',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 8,
        languageId: keyEnglish,
        categoryName: 'Mexican',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 8,
        languageId: keyHindi,
        categoryName: 'मैक्सिकन',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 9,
        languageId: keyEnglish,
        categoryName: 'Japanese',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 9,
        languageId: keyHindi,
        categoryName: 'जापानी',
        imageUrl: ImageConstant.imagesIcDosa),
    CategoryModel(
        categoryId: 10,
        languageId: keyEnglish,
        categoryName: 'Noodles',
        imageUrl: ImageConstant.imagesIcPasta),
    CategoryModel(
        categoryId: 10,
        languageId: keyHindi,
        categoryName: 'नूडल्स',
        imageUrl: ImageConstant.imagesIcPasta),
  ];
  static List<CategoryMainModel> categoryMainList = <CategoryMainModel>[
    CategoryMainModel(categoryName: 'South Indian'),
    CategoryMainModel(categoryName: 'Italian'),
    CategoryMainModel(categoryName: 'Chinese'),
    CategoryMainModel(categoryName: 'Indian'),
    CategoryMainModel(categoryName: 'Beverages'),
    CategoryMainModel(categoryName: 'Burgers'),
    CategoryMainModel(categoryName: 'Salads'),
    CategoryMainModel(categoryName: 'Mexican'),
    CategoryMainModel(categoryName: 'Japanese'),
    CategoryMainModel(categoryName: 'Noodles'),
  ];
  static List<Map<String, dynamic>> dineInMainTableList = [
    {
      DatabaseValues.columnSeatSize: 2,
    },
    {
      DatabaseValues.columnSeatSize: 4,
    },
    {
      DatabaseValues.columnSeatSize: 6,
    },
  ];
  static List<Map<String, dynamic>> dineInTableList = [
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 1,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 3,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 5,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 1,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 3,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnIsAvailable: 1,
    },
    {
      DatabaseValues.columnTableId: 2,
      DatabaseValues.columnOutletId: 6,
      DatabaseValues.columnIsAvailable: 1,
    },
  ];

}
